version: 2.1
orbs:
  yarn: itinerisltd/yarn@0.4.0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - yarn/install
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: /tmp/dist
          paths:
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Prettier
          command: yarn run prettier
      - run:
          name: Lint
          command: yarn run tslint
      - run:
          name: Chromatic
          command: yarn run chromatic
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - yarn/install
      - attach_workspace:
          at: dist
      - add_ssh_keys:
          fingerprints:
            - "3e:7f:fb:32:0a:b7:3f:3f:8f:c8:2d:92:86:5e:34:01"
      - run:
          name: Deploy
          command: yarn run ship
workflow:
  build:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
