version: 2.0
jobs:
  depedencies: &job
    docker:
      - image: catsoss/node-headless-chrome:latest
    steps:
      - checkout
      - &node_modules
        restore_cache:
          name: Restore node modules
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save node modules
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  build:
    <<: *job
    steps:
      - checkout
      - *node_modules
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    <<: *job
    steps:
      - checkout
      - *node_modules
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Snapshot
          command: yarn run snapshot
  deploy:
   <<: *job
    steps:
      - checkout
      - *node_modules
      - attach_workspace:
          at: .
      - run:
          name: Setup Git
          command: |
            git config user.email "cid@circleci.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "4c:47:89:e6:a4:7c:05:e1:bf:04:81:c8:dc:28:9e:fc"
      - run:
          name: Deploy
          command: yarn run ship
workflows:
  version: 2
  workflow:
    jobs:
      - depedencies
      - test:
          requires:
            - depedencies
      - build:
          requires:
            - depedencies
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
