version: 2.0
jobs:
  depedencies:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prettier
          command: yarn run prettier
      - run:
          name: Lint
          command: yarn run tslint
      - run:
          name: Snapshot
          command: yarn run snapshot
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Git
          command: |
            git config user.email "cid@circleci.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "4c:47:89:e6:a4:7c:05:e1:bf:04:81:c8:dc:28:9e:fc"
      - run:
          name: Deploy
          command: yarn run ship
workflows:
  version: 2
  workflow:
    jobs:
      - depedencies
      - test:
          requires:
            - depedencies
      - build:
          requires:
            - depedencies
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
