name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build